version: '3'
services:
  server:
    build: 
      context: ./server
      target: production
    volumes:
      - ./server:/app/server:ro
    environment:
      - NODE_ENV=production
    command: npm run prod
    
    